[package]
name = "tougou_bot"
version = "1.0.0"
authors = ["Alexander Hammatt <alexander.hammatt@protonmail.com>"]
edition = "2018"

[dependencies]
serenity = { git = "https://github.com/serenity-rs/serenity/", branch = "v0.6.x" }
reqwest = "0.9"