[package]
name = "tougou_bot"
version = "2.0.1"
authors = ["Alexander Hammatt <alexander.hammatt@protonmail.com>"]
edition = "2018"

[dependencies]
env_logger = "0.6"
log = "0.4"
reqwest = "0.9"
rusqlite = "0.18"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serenity = "0.6.0-rc.0"